name: video_editor_example
description: The example project for the video_editor package.

publish_to: "none" 
version: 3.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_editor:
    path: ../

  fraction: ^5.0.2
  image_picker: ^1.0.4
  path: ^1.8.3
  video_player: ^2.8.1
  ffmpeg_kit_flutter_min: ^6.0.3
  screenshot: ^2.3.0
  colorfilter_generator: ^0.0.8
  lindi_sticker_widget: ^0.1.1
  text_editor: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.ttf
    - family: AlexBrush
      fonts:
        - asset: fonts/AlexBrush-Regular.ttf
    - family: Allura
      fonts:
        - asset: fonts/Allura-Regular.otf
    - family: Arizonia
      fonts:
        - asset: fonts/Arizonia-Regular.ttf
    - family: ChunkFive
      fonts:
        - asset: fonts/ChunkFive-Regular.otf
    - family: GrandHotel
      fonts:
        - asset: fonts/GrandHotel-Regular.otf
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.otf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster_1.3.otf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: OstrichSans
      fonts:
        - asset: fonts/OstrichSans-Medium.otf
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.otf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: SEASRN
      fonts:
        - asset: fonts/SEASRN.ttf
    - family: Windsong
      fonts:
        - asset: fonts/Windsong.ttf